name: melpazoid
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install emacs && emacs --version
          git clone -b support-vterm https://github.com/vale981/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: (py-vterm-interaction :repo "vale981/py-vterm-interaction.el" :fetcher github)
          # set this to false (or remove it) if the package isn't on MELPA:
          EXIST_OK: false
        run: |
          echo $GITHUB_REF && make -C ~/melpazoid
